###
# https://probot.github.io/apps/settings/
#
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  has_issues: true
  has_wiki: false
  has_pages: false
  default_branch: devel
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  # States
  - name: ci_verified
    color: b60205
    description: Push fixes to PR branch to re-run CI.
  - name: needs_ci
    color: b60205
    description: This PR requires CI testing to be performed. Please close and re-open this PR to trigger CI.
  - name: merge_commit
    color: d93f0b
    description: This PR contains at least one merge commit. Please resolve!
  - name: needs_rebase
    color: d93f0b
    description: https://docs.ansible.com/ansible/devel/dev_guide/developing_rebasing.html
  - name: needs_info
    color: d93f0b
    description: This issue requires further information. Please answer any outstanding questions.
  - name: needs_revision
    color: d93f0b
    description: This PR fails CI tests or a maintainer has requested a review/revision of the PR.
  - name: needs_template
    color: d93f0b
    description: This issue/PR has an incomplete description. Please fill in the proposed template correctly.
  - name: stale_ci
    color: d93f0b
  - name: waiting_on_contributor
    color: d93f0b
    description: Needs help. Feel free to engage to get things unblocked.
  - name: new_inventory
    color: c2e0c6
  - name: new_plugin
    color: c2e0c6
  - name: new_module
    color: c2e0c6
  - name: new_module_directory
    color: c2e0c6
  - name: new_contributor
    color: 8aea94
  - name: bug
    color: fbca04
    description: This issue/PR relates to a bug.
  - name: feature
    color: 006b75
    description: This issue/PR relates to a feature request.
  - name: has_issue
    color: ededed
  - name: has_pr
    color: ededed
  - name: owner_pr
    color: 0e8a16
  - name: pr_day
    color: 0e8a16
    description: Has been reviewed during a PR review Day. https://github.com/ansible/community/issues/407
  # components
  - name: action
    color: 71bc1c
  - name: become
    color: 71bc1c
  - name: cache
    color: 71bc1c
  - name: callback
    color: 71bc1c
  - name: cliconf
    color: 71bc1c
  - name: connection
    color: 71bc1c
  - name: docs_fragments
    color: 71bc1c
  - name: filter
    color: 71bc1c
  - name: httpapi
    color: 71bc1c
  - name: integration
    color: 71bc1c
  - name: inventory
    color: 71bc1c
  - name: lookup
    color: 71bc1c
  - name: plugin
    color: 71bc1c
  - name: module
    color: 71bc1c
  - name: module_utils
    color: 71bc1c
  - name: netconf
    color: 71bc1c
  - name: shell
    color: 71bc1c
  - name: strategy
    color: 71bc1c
  - name: terminal
    color: 71bc1c
  - name: tests
    color: 71bc1c
  - name: units
    color: 71bc1c
  - name: vars
    color: 71bc1c
branches:
 - name: devel
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        teams: []
